### PR TITLE
Temporarily ignore stdout and stderr from cling processor during inspection requests

### LINKED ISSUE #39: [Introspection] More errors captures on inspection
Now that we are capturing more exception and content from stdout and stderr, there is some content from the `stderr` stream displayed in the notebook upon call of the `??` magic.

help

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Fixes #39

### CODE REVIEW

File: src/xcpp_interpreter.cpp [hunk 1]
```diff
@@ -63,101 +63,80 @@ namespace xeus
...
-            if (is_to_inspect)
+            if (std::regex_search(block, re))
             {
-                block_to_inspect = block;
-
-                std::vector<std::string> lines = get_lines(block);
-
-                // Get the line before the introspection demand (given by ??)
-                block = "";
-                for (auto line : lines)
```
Comment (SylvainCorlay) [inline src/xcpp_interpreter.cpp]: @gouarin, the `block` variable that you compute here was never used.

File: src/xinspect.hpp [hunk 2]
```diff
@@ -72,13 +72,28 @@ namespace xeus
...
+            auto cerr_strbuf = std::cerr.rdbuf();
+            auto null = xnull();
+            std::cout.rdbuf(&null);
+            std::cerr.rdbuf(&null);
+
+            errorlevel = m_processor.process(code.c_str(), compilation_result, &result);
+
+            std::cout.rdbuf(cout_strbuf);
+            std::cerr.rdbuf(cerr_strbuf);
+        }
```
Comment (SylvainCorlay) [inline src/xinspect.hpp]: This is the code that temporarily dismisses the output from `std::cerr` and `std::cout` during the call to `m_processor.process()` required for getting the type id.
